p = Project.create(title: "Семья" )
Todo.create(text: "Купить молоко", isCompleted: false, project_id: p.id)
Todo.create(text: "Заменить масло в двигателе до 23 апреля", isCompleted: false, project_id: p.id)
Todo.create(text: "Отправить письмо бабушке", isCompleted: true, project_id: p.id)
Todo.create(text: "Заплатить за квартиру", isCompleted: false, project_id: p.id)
Todo.create(text: "Забрать обувь из ремонта", isCompleted: false, project_id: p.id)

p2 = Project.create(title: "Работа" )
Todo.create(text: "Позвонить заказчику", isCompleted: true, project_id: p2.id)
Todo.create(text: "Отправить документы", isCompleted: true, project_id: p2.id)
Todo.create(text: "Заполнить отчет", isCompleted: false, project_id: p2.id)

p3 = Project.create(title: "Прочее" )
Todo.create(text: "Позвонить другу", isCompleted: false, project_id: p3.id)
Todo.create(text: "Подготовиться к поездке", isCompleted: false, project_id: p3.id)
